use worker;
SELECT * FROM Worker ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;
SELECT * FROM Worker WHERE FIRST_NAME IN ('Vipul', 'Satish');
SELECT * FROM Worker WHERE FIRST_NAME LIKE '_____h';
SELECT * FROM Worker WHERE SALARY BETWEEN 50000 AND 80000;
SELECT FIRST_NAME, LAST_NAME, COUNT(*) FROM Worker GROUP BY FIRST_NAME, LAST_NAME HAVING COUNT(*) > 1;
SELECT * FROM Worker LIMIT 6;
SELECT DEPARTMENT, COUNT(*) as NumOfWorkers FROM Worker GROUP BY DEPARTMENT HAVING COUNT(*) < 5;
SELECT DEPARTMENT, COUNT(*) as NumOfWorkers FROM Worker GROUP BY DEPARTMENT;
SELECT W.FIRST_NAME, W.DEPARTMENT, W.SALARY FROM Worker W INNER JOIN (SELECT DEPARTMENT, MAX(SALARY) AS MaxSalary FROM Worker GROUP BY DEPARTMENT
) AS D ON W.DEPARTMENT = D.DEPARTMENT AND W.SALARY = D.MaxSalary;